const SCENARIOS = [
  {
    id: 'seizure',
    title: 'IRGC SEIZURE OF UAE-FLAGGED TANKER',
    rung: 'SEIZURE',
    rungColor: '#ffaa00',
    threat: 'HIGH',
    summary: 'IRGC fast attack craft have intercepted and boarded the UAE-flagged tanker GULF MERIDIAN in the international shipping channel near Abu Musa. The crew is being held aboard. Tehran cites alleged "shipping safety violations." Allied attribution is high.',
    coverStory: 'IRGC public statement frames the seizure as a "lawful inspection" under Iranian maritime authority.',
    keyVessels: ['civ-meridian','civ-blue-1','civ-allied-1'],
    keyVesselCategories: [4, 5, 11], // Saudi crude, UAE, European commercial
    initialIndicators: {
      escalationRung: 2,
      oilPrice: 84,
      warRiskInsurance: 145,
      allianceCohesion: 72,
      attributionConfidence: 81,
      iranCoercion: 38,
    },
    turns: [
      {
        inject: 'IRGC has begun a public live broadcast from the bridge of GULF MERIDIAN. Two additional fast-attack craft have positioned at the western edge of the strait. Saudi Aramco signals it may delay tomorrow morning crude departures pending convoy arrangements.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Issue coordinated public attribution with UK, France, UAE',
            branch:'diplomatic',
            assessment:'Joint statement lands within 2 hours. Tehran accuses signatories of "war propaganda." UAE confidence rises. China declines to co-sign — modest fracture in the broader coalition. Attribution confidence ticks up; alliance cohesion holds.',
            deltas:{ allianceCohesion:+2, attributionConfidence:+5, iranCoercion:+1 } },
          { lane:'INFORMATION', title:'Push real-time IMINT/SIGINT to allied capitals',
            assessment:'NSA and partner agencies share unredacted track data on the IRGC craft. Allies move from "high confidence" to "very high confidence" attribution. Intelligence sources risk exposure if the imagery is leaked publicly. Tehran shifts narrative to claim the imagery is fabricated.',
            deltas:{ attributionConfidence:+8, allianceCohesion:+1 } },
          { lane:'MILITARY', title:'Forward-deploy USS-flagged escort within visual range',
            branch:'escalation',
            assessment:'A DDG repositions to within 12 nm of GULF MERIDIAN. IRGC reads the move as escalation but does not increase posture. Civilian shipping insurers note the visible Blue presence — war-risk premiums tick down marginally. Iran coercion reading climbs as IRGC sees Blue commitment.',
            deltas:{ warRiskInsurance:-5, iranCoercion:+4, allianceCohesion:+2 } },
          { lane:'ECONOMIC', title:'Activate war-risk insurance backstop with Lloyd\'s',
            assessment:'Treasury commits to underwrite Lloyd\'s war-risk syndicate exposure for transits through the strait. War-risk premiums reverse. Industry confidence in Blue commitment rises. Tehran loses one lever of economic pressure.',
            deltas:{ warRiskInsurance:-15, oilPrice:-2 } },
          { lane:'INTELLIGENCE', title:'Re-task ISR + cue Sentinel-2 collection on IRGC ports',
            assessment:'Within 6 hours, fresh Sentinel-2 imagery confirms IRGC reinforcement craft at Bandar Abbas. VLM analysis flags two additional fast-attack hulls under cover at the docks. Tehran is unaware of the collection but adapts within 24 hours.',
            deltas:{ attributionConfidence:+4, iranCoercion:+1 } },
        ],
      },
      {
        inject: 'Tehran refuses release of GULF MERIDIAN crew. UAE has formally requested U.S. assistance. Oil traders have priced in a 4% Brent premium overnight. CSIS analysts publish a thread arguing Iran is "testing the new floor of acceptable coercion."',
        decisions: [
          { lane:'DIPLOMATIC', title:'Escalate to UN Security Council emergency session',
            assessment:'Russia and China block any binding resolution but a non-binding statement of concern passes 13-2. Tehran is internationally isolated but materially unconstrained. The diplomatic record is established for any future Blue military action.',
            deltas:{ allianceCohesion:+3, iranCoercion:+2 } },
          { lane:'INFORMATION', title:'Run public attribution campaign with declassified imagery',
            assessment:'Selected Sentinel-2 + commercial SAR imagery is released. International press picks up the story within 4 hours. Domestic Iranian media is forced to address the imagery; public Iranian government denial undermines Tehran\'s information narrative globally.',
            deltas:{ attributionConfidence:+6, iranCoercion:+3 } },
          { lane:'MILITARY', title:'Establish convoy escort for outbound UAE traffic',
            assessment:'Two DDGs and a UK Type-23 begin escorting UAE-flagged tankers out of the strait. IRGC declines to challenge active escort. Throughput recovers but at the cost of forward-deployed combat power consumed in escort duty.',
            deltas:{ warRiskInsurance:-10, oilPrice:-3, iranCoercion:+3 } },
          { lane:'ECONOMIC', title:'Coordinate SPR release with IEA partners',
            assessment:'The U.S. announces a 30M-barrel SPR draw coordinated with Japan, Korea, and the IEA. Brent retraces 2.5%. The signal of joint action reassures markets but consumes a strategic reserve lever for limited operational benefit.',
            deltas:{ oilPrice:-5, allianceCohesion:+1 } },
          { lane:'INTELLIGENCE', title:'Activate covert channel to Omani mediator',
            assessment:'Muscat carries a private message to Tehran offering face-saving release pathway. Tehran does not commit but the channel remains open. Omani relations improve; Iran reads the back-channel as Blue weakness alongside public escalation.',
            deltas:{ allianceCohesion:+2, iranCoercion:-2 } },
        ],
      },
      {
        inject: 'IRGC announces "investigative procedures" will continue for 30 days. Two additional civilian tankers turn around at the eastern strait entrance, citing insurance unavailability. A Chinese-owned VLCC requests Iranian naval escort westbound — Tehran assents, framing it as a "service to legitimate commerce."',
        decisions: [
          { lane:'DIPLOMATIC', title:'Demarche Beijing on Chinese-flagged Iranian escort',
            assessment:'A discreet but firm message is delivered through PRC channels. Beijing instructs the China-flagged operator to refuse Iranian escort going forward. The maneuver succeeds but Tehran reads it as evidence Beijing is constrainable by U.S. pressure.',
            deltas:{ attributionConfidence:+2, iranCoercion:+2, allianceCohesion:+1 } },
          { lane:'INFORMATION', title:'Cyber operation against IRGC public broadcast infrastructure',
            assessment:'IRGC livestream goes dark for 6 hours. Tehran cannot publicly acknowledge the attribution. Domestic Iranian commentary turns critical of the IRGC information campaign. Cyber capability is now exposed to Iranian counter-investigation.',
            deltas:{ iranCoercion:+4, attributionConfidence:+1 } },
          { lane:'MILITARY', title:'Authorize visit, board, search, seizure (VBSS) of GULF MERIDIAN',
            assessment:'CTF 152 plans the operation. Risk of casualties is non-trivial — IRGC has 14 personnel aboard. The operation if executed restores the vessel; if it fails, escalation rung jumps to STRIKE. PLAN APPROVED, NOT EXECUTED — held for next turn.',
            deltas:{ iranCoercion:+5, escalationRung:+1, warRiskInsurance:+8 } },
          { lane:'ECONOMIC', title:'Sanction IRGC Navy commander + 3 vessels (OFAC SDN)',
            assessment:'Treasury designates the IRGC Navy commander and the three IRGC craft involved in the boarding. Material impact is low. Symbolic impact is significant. Tehran responds by publicly elevating the named commander\'s status.',
            deltas:{ iranCoercion:+1, attributionConfidence:+1 } },
          { lane:'INTELLIGENCE', title:'Run live VLM analysis on real Sentinel-2 pass over the strait',
            assessment:'A real-time Sentinel-2 frame is captured during the active turn. Llama 3.2 Vision identifies 3 IRGC craft, 1 disabled merchant hulk, dispersed civilian traffic. The analysis is fed into the Blue Cell sitrep. (Demo touchpoint.)',
            deltas:{ attributionConfidence:+3 } },
        ],
      },
      {
        inject: 'Tehran indicates willingness to "consider release" if Western escort operations cease and the Lloyd\'s war-risk backstop is withdrawn. Allied capitals are split: UAE wants the crew home; UK wants no concessions; Riyadh wants the convoy operation continued indefinitely. CSIS publishes a follow-on note arguing this is the off-ramp turn.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Accept Omani-mediated release in exchange for ceasing escort',
            assessment:'Crew is released within 48 hours. Escort operations end. Tehran achieves a partial coercion victory — establishing that escort deployments are negotiable. Coalition members read the outcome differently. The exercise ends with the immediate crisis resolved but Iran emboldened.',
            deltas:{ iranCoercion:+8, allianceCohesion:-4, warRiskInsurance:-20, oilPrice:-3 } },
          { lane:'INFORMATION', title:'Publicly reject all conditions, double down on attribution case',
            assessment:'Tehran loses the off-ramp it offered. Domestic Iranian pressure on Khamenei to release the crew quietly without conditions builds. Crew is released within 14 days without formal Blue concessions. Iran retains coercion capacity but at reputational cost.',
            deltas:{ iranCoercion:-3, attributionConfidence:+4, allianceCohesion:+3 } },
          { lane:'MILITARY', title:'Execute VBSS against GULF MERIDIAN now',
            assessment:'Operation succeeds with 1 IRGC KIA, 0 Blue casualties, crew rescued. Tehran responds with a missile strike on a Saudi tanker 36 hours later — the exercise escalates to STRIKE rung. Crisis is no longer contained.',
            deltas:{ escalationRung:+2, allianceCohesion:+2, iranCoercion:-2, warRiskInsurance:+30 },
            mapEffect:{ mmsi:477001234, type:'BOARDED' } },
          { lane:'ECONOMIC', title:'Maintain insurance backstop + escort indefinitely',
            assessment:'Tehran calculates the cost of indefinite low-grade coercion exceeds the benefit. Crew is released within 21 days under "humanitarian" framing. Strait throughput normalizes. Blue commitment cost is real (DDG availability, Treasury exposure) but bounded.',
            deltas:{ iranCoercion:-4, allianceCohesion:+2, warRiskInsurance:-10, oilPrice:-2 } },
          { lane:'INTELLIGENCE', title:'Continue covert mediation, no public moves',
            assessment:'Crew is released within 30 days through quiet channels. The crisis fades from public attention but the underlying coercion dynamic is unresolved. Tehran reads the outcome as a successful application of pressure.',
            deltas:{ iranCoercion:+4, allianceCohesion:-1, warRiskInsurance:-10 } },
        ],
      },
    ],
    branches: {
      escalation: {
        inject: 'Blue\'s decision to forward-deploy USS NITZE within visual range of GULF MERIDIAN has electrified the operational environment. Tehran responded within 90 minutes: two additional IRGC fast-attack craft surged from Bandar Abbas, and IRGC spokesmen issued a public warning that any "hostile approach" to the vessel will be met with "proportional maritime defense." War-risk premiums spiked 18 bps on the news. Riyadh is watching the standoff and has paused its own convoy request pending Blue\'s next move.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Recall USS NITZE 20 nm to signal off-ramp to Tehran',
            assessment:'Pulling back creates visible de-escalation space. Tehran reads the withdrawal as Blue backing down under pressure. IRGC maintains posture but does not surge further. War-risk premiums settle. The tactical off-ramp is opened at the cost of demonstrated resolve.',
            deltas:{ iranCoercion:-3, allianceCohesion:-2, warRiskInsurance:-12 } },
          { lane:'INFORMATION', title:'Push live DDG track data to Lloyds + allied shipping registries',
            assessment:'Real-time Blue naval presence data is shared with insurers and flag states. War-risk premiums retrace 10 bps. IRGC cannot claim Blue is absent or passive. Tehran\'s information leverage over shipping costs is directly countered.',
            deltas:{ warRiskInsurance:-10, attributionConfidence:+3, allianceCohesion:+1 } },
          { lane:'MILITARY', title:'Add second DDG + establish Combat Air Patrol over the strait',
            assessment:'USS COLE surges from Bahrain. F/A-18 CAP is established at FL200 over the strait. IRGC does not escalate but shifts two fast-attack craft to hardened positions near Qeshm. Blue commitment is now unambiguous. Iran coercion calculus shifts against further aggression.',
            deltas:{ iranCoercion:+5, warRiskInsurance:-8, allianceCohesion:+3, escalationRung:+1 } },
          { lane:'ECONOMIC', title:'Invoke Lloyd\'s war-risk backstop — cap premiums at 150 bps',
            assessment:'Treasury activates the emergency backstop. Premiums cannot legally exceed 150 bps for covered transits. Commercial shipping begins to move again within 18 hours. Tehran loses the economic squeeze lever. Saudi Aramco resumes convoy requests.',
            deltas:{ warRiskInsurance:-18, oilPrice:-3, allianceCohesion:+2 } },
          { lane:'INTELLIGENCE', title:'Cyber operation against IRGC fast-attack craft C2 network',
            assessment:'NSA delivers a targeted intrusion degrading encrypted comms between Bandar Abbas and the forward FAC group. IRGC craft operate on fallback analog comms for 8 hours. Response lag increases; coordination degrades. Tehran cannot identify the intrusion source for 48 hours.',
            deltas:{ iranCoercion:+3, attributionConfidence:+2 } },
        ],
      },
      diplomatic: {
        inject: 'Blue\'s coordinated public attribution statement landed with force — but Tehran\'s counter-statement hit the wires within 3 hours, labeling the attribution "fabricated Western aggression." China has declined to co-sign the Blue statement privately and called the situation "a bilateral maritime misunderstanding." The UAE Foreign Minister is holding public comment. The attribution case is now a contested information battle, not a settled fact. Shipping insurers are watching whether the coalition holds.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Push attribution to UN Security Council for emergency session',
            assessment:'The UNSC session forces a global vote. Russia and China veto a binding resolution but 13 members endorse the Blue attribution case in a non-binding statement. Tehran is internationally isolated. The diplomatic record provides legal basis for further escalatory Blue action.',
            deltas:{ allianceCohesion:+3, attributionConfidence:+4, iranCoercion:+2 } },
          { lane:'INFORMATION', title:'Release Sentinel-2 + SAR imagery of the seizure in progress',
            assessment:'Declassified commercial-satellite imagery showing IRGC craft alongside GULF MERIDIAN is released to international press. Tehran\'s "lawful inspection" framing collapses within 6 hours. Domestic Iranian media is forced to address the imagery. Attribution confidence jumps.',
            deltas:{ attributionConfidence:+10, iranCoercion:+3 } },
          { lane:'MILITARY', title:'Low-key military shadow — one P-8 Poseidon ISR orbit, not publicized',
            assessment:'A P-8 maintains a discreet surveillance orbit broadcasting IRGC vessel positions to allied shipping. Not press-announced. Tehran detects the aircraft but cannot respond publicly without confirming their awareness of the attribution case. Blue ISR picture sharpens.',
            deltas:{ attributionConfidence:+5, iranCoercion:+1 } },
          { lane:'ECONOMIC', title:'Signal SPR readiness to markets without executing a draw',
            assessment:'Treasury and IEA jointly signal preparedness to release strategic reserves if premiums spike further. Brent retraces 1.5%. Insurers note the reserve backstop. No reserves consumed. Tehran loses the oil-price-shock lever without Blue expending strategic capital.',
            deltas:{ oilPrice:-2, warRiskInsurance:-6 } },
          { lane:'INTELLIGENCE', title:'Protect sources — limit imagery release to non-attributable package',
            assessment:'Legal reviews determine the Sentinel-2 release plan to avoid burning HUMINT or SIGINT collection methods. The attribution package is carefully sanitized. Collection capacity is preserved for Turn 3-4 contingencies. Short-term attribution case is slightly less damaging to Tehran but sources are protected.',
            deltas:{ attributionConfidence:+4, allianceCohesion:+1 } },
        ],
      },
    },
  },
  // ════════════════════════════════════════════════════════════════════════════
  // MINING — limpet mines on Saudi crude tanker
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'mining',
    title: 'LIMPET MINE STRIKE ON SAUDI CRUDE TANKER',
    rung: 'MINING',
    rungColor: '#ff7700',
    threat: 'CRITICAL',
    summary: 'A limpet mine has detonated below the waterline of the Saudi-flagged VLCC ALPINE CONFIDENCE near Fujairah. The vessel is taking on water; crew has abandoned ship. Iran denies responsibility. CENTCOM divers recover one un-detonated mine — IRGC fingerprint is "very high confidence" but not yet public.',
    coverStory: 'Iran denies any role and suggests Israeli or third-party false-flag activity.',
    keyVessels: ['civ-rastanura','civ-uae-1','civ-blue-1'],
    keyVesselCategories: [4, 5, 11],
    initialIndicators: { escalationRung:3, oilPrice:91, warRiskInsurance:210, allianceCohesion:75, attributionConfidence:62, iranCoercion:46 },
    turns: [
      {
        inject: 'Brent has spiked $7 overnight. Lloyd\'s war-risk premium for strait transits has tripled. Riyadh demands U.S. action; UAE prefers de-escalation; the unexploded mine is en route to FBI lab for forensic analysis. CSIS publishes a thread arguing this is a deliberate ambiguity play.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Public attribution release with forensic mine evidence',
            branch:'diplomatic',
            assessment:'Forensic evidence is released with imagery of the recovered mine — IRGC manufacturer markings are visible. Iranian denial collapses internationally. Coalition tightens. Domestic Iranian commentary becomes incoherent. Attribution confidence climbs sharply.',
            deltas:{ attributionConfidence:+18, allianceCohesion:+3, iranCoercion:+2 } },
          { lane:'INFORMATION', title:'Run cyber operation on IRGC naval logistics network',
            assessment:'Operation degrades IRGC mine-warfare command-and-control for 36 hours. Tehran cannot publicly attribute the attack but adapts within 4 days. The disruption window forces Iran to operate analog, slowing further mining ops.',
            deltas:{ iranCoercion:+5 } },
          { lane:'MILITARY', title:'Stand up multi-national mine-counter-measures task force',
            branch:'escalation',
            assessment:'CTF 152 expands to include UK, French, Australian MCM assets. Strait transits resume under MCM screen within 96 hours. Iran reads the move as containment but no further mining attempts. Insurance premiums begin to retrace.',
            deltas:{ warRiskInsurance:-30, oilPrice:-4, allianceCohesion:+4, iranCoercion:+3 },
            mapEffect:{ mmsi:477001234, type:'CONVOY_FORM' } },
          { lane:'ECONOMIC', title:'Coordinate massive SPR + IEA release (90M bbl)',
            assessment:'Brent retraces 6%. Markets read the joint commitment as durable. Strategic reserve is significantly depleted; future leverage is reduced. Saudi appreciation is real but partial — Riyadh wanted military response, not financial.',
            deltas:{ oilPrice:-9, allianceCohesion:+1 } },
          { lane:'INTELLIGENCE', title:'Live VLM analysis of mine forensics + Sentinel-2 IRGC base imagery',
            assessment:'Llama 3.2 Vision matches manufacturing markings on the recovered mine to imagery of IRGC depots at Bandar Abbas. Confidence is reportable but not chargeable. Provides the basis for the public attribution case in DIPLOMATIC.',
            deltas:{ attributionConfidence:+8 } },
        ],
      },
      {
        inject: 'A second limpet mine is found inert on a Greek-flagged tanker exiting the strait, suggesting an attempted but failed second attack. Iran offers "humanitarian assistance" with the ALPINE CONFIDENCE salvage — a diplomatic taunt. Riyadh moves a destroyer toward the strait independently.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Coordinate Saudi destroyer movement under Blue command',
            assessment:'Riyadh accepts CTF integration. Saudi DDG enters the multinational MCM task force. Coalition presence visibly grows. Tehran reads the integration as a threshold crossed — Saudi-U.S. military synchronization is now real.',
            deltas:{ allianceCohesion:+5, iranCoercion:+4 } },
          { lane:'INFORMATION', title:'Release intercepted IRGC communications about mining plan',
            assessment:'Communications published in cleaned form. Iran denies authenticity. Domestic Iranian skepticism of government denial deepens. Sources at risk; one collection method is burned. Coalition attribution case becomes airtight.',
            deltas:{ attributionConfidence:+10, iranCoercion:+3 } },
          { lane:'MILITARY', title:'Pre-emptive strike on identified IRGC mining staging area',
            assessment:'Tomahawks strike a coastal IRGC compound at night. 14 IRGC KIA, no civilian casualties. Iran retaliates by firing two ASCMs at a Western tanker in the strait 40 hours later. Exercise escalates to STRIKE rung. Crisis is no longer contained.',
            deltas:{ escalationRung:+1, iranCoercion:-2, allianceCohesion:+1, warRiskInsurance:+45 },
            mapEffect:{ mmsi:636091234, type:'STRIKE' } },
          { lane:'ECONOMIC', title:'Designate IRGC-N as Foreign Terrorist Organization',
            assessment:'OFAC adds IRGC-N to the FTO list. Material impact is symbolic; existing IRGC sanctions are already comprehensive. Iran responds with an asymmetric naval signal but no new mining. Domestic Iranian regime hardliners gain leverage.',
            deltas:{ iranCoercion:+1 } },
          { lane:'INTELLIGENCE', title:'Surge ISR over IRGC bases for forward posture monitoring',
            assessment:'Coverage catches a mid-week IRGC posture relaxation — mining operation is paused. Insurance markets tentatively recover. Without public release of the indication, allied policymakers cannot use the intel for deterrent signaling.',
            deltas:{ warRiskInsurance:-10, attributionConfidence:+2 } },
        ],
      },
      {
        inject: 'Insurance market is in chaos. Two major shipping lines have suspended Strait routing. Brent stays elevated. Tehran offers "regional dialogue" if all U.S. military assets withdraw to pre-crisis positions. Beijing publicly endorses the proposal. UN SecGen schedules emergency session.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Reject Tehran offer; counter with conditional de-escalation framework',
            assessment:'Counter-offer: cessation of mining + crew of ALPINE CONFIDENCE repatriated + IRGC public statement disavowing. Tehran refuses publicly but discreetly initiates Omani back-channel. Off-ramp is structurally available even as public posture stays hostile.',
            deltas:{ iranCoercion:-3, allianceCohesion:+2 } },
          { lane:'INFORMATION', title:'Saturate global media with VLM-verified mine forensics',
            assessment:'Coordinated information release: 12 major outlets receive briefing packages. Visual narrative becomes uncontested. Domestic Iranian elite signaling shifts. Beijing quietly distances. Tehran reads the information environment as adverse.',
            deltas:{ attributionConfidence:+12, iranCoercion:+2 } },
          { lane:'MILITARY', title:'Maintain MCM operations + escort tempo, no further strikes',
            assessment:'Coalition holds posture. Tehran calculates further mining is cost-ineffective given visible MCM coverage. Mining campaign quietly ends within 10 days. Crisis remains active but bounded. Throughput slowly recovers.',
            deltas:{ warRiskInsurance:-20, oilPrice:-4, iranCoercion:-3 } },
          { lane:'ECONOMIC', title:'Sanction Iranian crude buyers in third-country jurisdictions',
            assessment:'Secondary sanctions notices issued to Indian, Turkish, and PRC refiners taking Iranian crude. Iranian export volumes drop 12% within 30 days. Iran feels material economic pressure but reads the move as Blue overreach.',
            deltas:{ iranCoercion:+3 } },
          { lane:'INTELLIGENCE', title:'Run RAG-augmented INTEL CHAT briefing for principals',
            assessment:'INTEL CHAT pulls JP 3-32 + CSIS Hormuz analyses + ACLED recent regional events into a synthesized brief for principals. Decision quality improves. (Demo touchpoint — INTEL CHAT used in real time.)',
            deltas:{ attributionConfidence:+3 } },
        ],
      },
      {
        inject: 'Mining campaign appears to have ended. Tehran wants visible Blue concessions to declare victory. Coalition is unified but stretched. Allied capitals want the off-ramp. Riyadh wants a permanent presence. Domestic Iranian regime needs a face-saver.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Public crisis resolution agreement via Oman + UAE mediation',
            assessment:'Agreement: Iran disavows mining campaign; Blue draws down by 30% over 60 days; freedom of navigation reaffirmed. Crisis resolves at MINING rung without further escalation. Both sides claim partial victory.',
            deltas:{ iranCoercion:-5, allianceCohesion:+3, warRiskInsurance:-50, oilPrice:-6 } },
          { lane:'INFORMATION', title:'Maintain attribution case publicly indefinitely',
            assessment:'Tehran cannot rebuild operational legitimacy in the strait. Mining stays off the table for 18+ months. Crisis fades but no formal closure — ambiguity persists. Insurance recovery is slow.',
            deltas:{ iranCoercion:-2, allianceCohesion:+2, warRiskInsurance:-25 } },
          { lane:'MILITARY', title:'Establish permanent MCM forward presence at Fujairah',
            assessment:'Multi-national MCM presence formalized. Iran reads the presence as containment infrastructure. Saudi-UAE-U.S. trilateral defense cooperation deepens. Long-term Iranian deterrent posture in the strait shifts adversely.',
            deltas:{ iranCoercion:-6, allianceCohesion:+5, warRiskInsurance:-40 } },
          { lane:'ECONOMIC', title:'Permanent Lloyd\'s war-risk backstop with cost-share to Gulf partners',
            assessment:'Insurance backstop becomes structural. Strait commercial risk is institutionally absorbed. Iran loses the insurance lever for future coercion. Treasury exposure is durable but defined.',
            deltas:{ iranCoercion:-4, warRiskInsurance:-60, oilPrice:-3 } },
          { lane:'INTELLIGENCE', title:'Continue ISR posture; classified after-action with allies',
            assessment:'Crisis fades. Allied IC partnerships strengthen. Public closure absent. Iran reconsiders mine warfare doctrine but does not abandon it. Crisis is paused, not concluded.',
            deltas:{ allianceCohesion:+2, warRiskInsurance:-15 } },
        ],
      },
    ],
    branches: {
      escalation: {
        inject: 'The multinational MCM task force stood up rapidly — but Tehran reads the response as a containment architecture rather than a de-escalation gesture. A second mine was found inert on a Greek-flagged tanker, suggesting an attempted but failed second attack. Riyadh, interpreting Blue action as permission to act, has independently moved a Saudi destroyer toward the strait without consulting CTF 152. IRGC spokesmen have warned that "any hostile naval buildup will be met in kind." Insurance markets remain volatile. Coalition coordination is fraying at the edges.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Emergency demarche to Riyadh: integrate Saudi DDG into CTF or stand down',
            assessment:'Riyadh accepts integration under diplomatic pressure but only after 6-hour delay. Saudi DDG joins CTF 152. Coalition coherence is restored but the episode signals Gulf partners are willing to act unilaterally. Tehran reads the delay as Blue command-and-control weakness.',
            deltas:{ allianceCohesion:+4, iranCoercion:+2 } },
          { lane:'INFORMATION', title:'Publicly release mine forensics with manufacturer-serial match',
            assessment:'Forensic package released: IRGC mine design, serial numbers traced to Bandar Abbas depot. Iranian denial collapses globally within 8 hours. Domestic Iranian press is forced to cover the attribution. Tehran\'s regional information credibility drops sharply.',
            deltas:{ attributionConfidence:+12, iranCoercion:+4, allianceCohesion:+2 } },
          { lane:'MILITARY', title:'Pre-emptive strike on IRGC mine-warfare staging area at Bandar Abbas',
            assessment:'Tomahawks strike the coastal IRGC compound. 14 IRGC KIA, no civilian casualties. Iran retaliates by firing two ASCMs at a Western tanker 40 hours later. Crisis escalates to STRIKE rung. The mine-laying capability is materially degraded.',
            deltas:{ escalationRung:+1, iranCoercion:-2, allianceCohesion:+1, warRiskInsurance:+45 },
            mapEffect:{ mmsi:636091234, type:'STRIKE' } },
          { lane:'ECONOMIC', title:'Coordinate emergency SPR draw to hold Brent below $95',
            assessment:'A 50M-barrel joint IEA draw is announced. Brent retraces 4%. Markets read the coordinated action as durable Blue commitment. Strategic reserve is partially depleted but the price shock lever is neutralized for the near term.',
            deltas:{ oilPrice:-6, allianceCohesion:+2, warRiskInsurance:-12 } },
          { lane:'INTELLIGENCE', title:'Surge ISR and share IRGC posture data with Saudi and UAE N2',
            assessment:'Gulf partners receive real-time IRGC mine-laying vessel tracking. Saudi and UAE naval commands can now act on shared intelligence. Coalition decision-making accelerates. Tehran cannot reposition mine-warfare assets without Blue and partner awareness.',
            deltas:{ attributionConfidence:+6, allianceCohesion:+3 } },
        ],
      },
      diplomatic: {
        inject: 'Blue\'s public release of forensic mine evidence with IRGC manufacturer markings has shattered Tehran\'s denial. Beijing has privately distanced itself from Iranian statements, telling U.S. back-channels that China "does not endorse mine warfare against commercial shipping." UAE Foreign Minister Sheikh Abdullah is privately pushing an off-ramp: a quiet Iranian commitment to cease mining in exchange for no further Blue military moves. The diplomatic window is open — but it requires Tehran to accept a public attribution loss.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Coordinate UAE-brokered cease-mining commitment with Tehran via Muscat',
            assessment:'Oman carries the message. Tehran privately commits to no further mining "during the current diplomatic window." No public acknowledgment. Crisis is functionally paused within 72 hours. Blue retains freedom to act if further mines appear.',
            deltas:{ iranCoercion:-4, allianceCohesion:+3, warRiskInsurance:-20 } },
          { lane:'INFORMATION', title:'Saturate global media with VLM-verified mine forensics for 72 hours',
            assessment:'Coordinated 12-outlet briefing package with annotated imagery. Visual narrative becomes uncontested globally. Domestic Iranian elite signaling shifts; Khamenei faces internal pressure to contain IRGC. Beijing publicly distances from Tehran.',
            deltas:{ attributionConfidence:+10, iranCoercion:+3, allianceCohesion:+1 } },
          { lane:'MILITARY', title:'Maintain MCM operations — restrained posture, no new escalation',
            assessment:'CTF 152 continues MCM sweeps without expanding rules of engagement. Tehran calculates further mining is cost-ineffective with MCM coverage visible. No new mines placed. Insurance premiums slowly retrace over 5 days.',
            deltas:{ warRiskInsurance:-15, oilPrice:-3, allianceCohesion:+2 } },
          { lane:'ECONOMIC', title:'Activate targeted IRGC-N sanctions — freeze mine-warfare procurement assets',
            assessment:'OFAC designates IRGC Naval Equipment Procurement Office and 4 front companies. Mine-warfare resupply is disrupted within 30 days. Material impact is medium-term. Tehran reads the designation as measured rather than maximalist — does not close the diplomatic window.',
            deltas:{ iranCoercion:+2, attributionConfidence:+2 } },
          { lane:'INTELLIGENCE', title:'Share Sentinel-2 mine-warehouse imagery with UAE and Omani mediators',
            assessment:'Satellite imagery of IRGC mine depots is shared with UAE and Omani mediators as leverage — showing Blue sees Iranian stockpiles. Mediators use the imagery to reinforce the off-ramp message to Tehran. Omani credibility with both sides increases.',
            deltas:{ allianceCohesion:+3, attributionConfidence:+4, iranCoercion:-2 } },
        ],
      },
    },
  },
  // ════════════════════════════════════════════════════════════════════════════
  // STRIKE — anti-ship missile salvo on US-flagged tanker
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'strike',
    title: 'ANTI-SHIP MISSILE SALVO ON U.S.-LINKED TANKER',
    rung: 'STRIKE',
    rungColor: '#cc2222',
    threat: 'CRITICAL',
    summary: 'IRGC has fired a salvo of three Noor-class anti-ship cruise missiles at the Marshall Islands-flagged tanker MAERSK HONAM transiting the strait. One missile hit, two were intercepted by USS SAMPSON CIWS. Vessel is on fire, crew evacuating. Three U.S. mariners aboard. Attribution is unambiguous — coastal IRGC battery near Bandar Abbas.',
    coverStory: 'Iran initially denies, then claims the launch was a "training exercise" with mistargeting.',
    keyVessels: ['civ-honam','civ-blue-1','civ-uae-1'],
    keyVesselCategories: [11, 13, 18],
    initialIndicators: { escalationRung:4, oilPrice:102, warRiskInsurance:350, allianceCohesion:80, attributionConfidence:92, iranCoercion:58 },
    turns: [
      {
        inject: 'MAERSK HONAM is on fire. Three U.S. mariners aboard; rescue underway. Brent up $11 in pre-market. Lloyd\'s suspends new war-risk policies on strait transits. Congressional leadership briefs imminent. Tehran has gone silent.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Brief allied capitals; coordinate joint statement of intent',
            branch:'diplomatic',
            assessment:'Allies align: UK, France, UAE, Japan, Korea sign a joint statement condemning the strike as a clear violation of international law. China and Russia decline. The diplomatic ground is set for a kinetic response with broad legitimacy.',
            deltas:{ allianceCohesion:+5, attributionConfidence:+4, iranCoercion:+2 } },
          { lane:'INFORMATION', title:'Release the missile track + radar tape publicly',
            assessment:'Real-time radar plots showing the IRGC battery launch are released through Pentagon press. Iranian "training exercise" cover story collapses within 6 hours. Domestic Iranian press is conflicted; regime narrative is on the defensive.',
            deltas:{ attributionConfidence:+8, iranCoercion:+4 } },
          { lane:'MILITARY', title:'Standoff strike on the firing IRGC coastal battery',
            branch:'escalation',
            assessment:'JASSM-ER strikes the Bandar Abbas battery from a B-1B. Battery destroyed. 22 IRGC KIA. Iran fires no follow-on. Tehran calculates further escalation is cost-prohibitive against demonstrated Blue capability. Insurance markets price in eventual de-escalation.',
            deltas:{ iranCoercion:-6, allianceCohesion:+3, warRiskInsurance:-40, escalationRung:0 },
            mapEffect:{ mmsi:229045678, type:'DISABLED' } },
          { lane:'ECONOMIC', title:'Emergency 120M bbl SPR release + freeze IRGC global assets',
            assessment:'Brent retraces $6. IRGC assets in 14 jurisdictions are frozen. Iranian regime liquidity squeezes. Tehran weighs banking-system fallout against face-saving messaging. Material economic pain is real.',
            deltas:{ oilPrice:-7, iranCoercion:+3 } },
          { lane:'INTELLIGENCE', title:'Run live VLM survey of all IRGC coastal batteries',
            assessment:'Sentinel-2 + commercial SAR runs identify 6 active IRGC ASCM positions. Llama 3.2 Vision flags two with apparent reload activity. Targeting picture for any further response is updated to current. (Demo touchpoint.)',
            deltas:{ attributionConfidence:+5 } },
        ],
      },
      {
        inject: 'MAERSK HONAM crew rescued, 2 injured, none killed. Vessel adrift. Tehran issues a "regret" statement framing the strike as an "operational error." Beijing calls for restraint on all sides. CSIS analysts argue the next 48 hours determine whether the crisis stays at STRIKE or escalates to CLOSURE.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Accept Iranian "regret" statement; pivot to off-ramp',
            assessment:'Tehran takes the off-ramp. Coalition accepts the formula publicly while retaining freedom to act privately. Crisis stabilizes at STRIKE rung. Iran has been deterred at significant cost; coercion capacity reduced for 12-18 months.',
            deltas:{ iranCoercion:-4, warRiskInsurance:-30, oilPrice:-4 } },
          { lane:'INFORMATION', title:'Reject "operational error" framing; insist on attribution',
            assessment:'Tehran loses the cover story. Domestic Iranian elite criticism of IRGC mounts. International isolation deepens. But Tehran cannot accept the framing without internal regime cost — risk of impulsive follow-on rises.',
            deltas:{ iranCoercion:-2, attributionConfidence:+5, escalationRung:+1 } },
          { lane:'MILITARY', title:'Establish 24/7 Combat Air Patrol over the strait',
            assessment:'F/A-18s from CVN-76 maintain continuous CAP. Iran cannot risk further surface launches without immediate detection and counter-strike. Operational tempo on Blue side is sustainable for 30-45 days. Beyond that, force rotation costs mount.',
            deltas:{ iranCoercion:-5, allianceCohesion:+2, warRiskInsurance:-20 } },
          { lane:'ECONOMIC', title:'Oil-export sanctions on Iran, full extraterritorial enforcement',
            assessment:'Iranian oil exports drop 60% within 90 days. Regime liquidity crisis deepens. Domestic Iranian protests grow. Crisis is weaponized economically; Iran reads it as regime-threat. Risk of asymmetric reprisal increases.',
            deltas:{ iranCoercion:-3, escalationRung:+1 } },
          { lane:'INTELLIGENCE', title:'Open mil-mil deconfliction channel via Omani intermediary',
            assessment:'Quiet line established. Both sides exchange real-time positional data on naval forces in the strait. Probability of accidental escalation drops sharply. Iran reads the channel as Blue de-escalation signal — coercion capacity partially restored.',
            deltas:{ iranCoercion:+1, allianceCohesion:+1 } },
        ],
      },
      {
        inject: 'Tensions stabilize at STRIKE rung. Iran has not launched again. Insurance market is recovering slowly. Iranian internal politics is fluid — IRGC leadership reshuffle rumored. Coalition military assets are at maximum forward deployment. Allies want clarity on long-term posture.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Negotiate formal de-escalation framework via Oman',
            assessment:'Six-week negotiation produces: Iran disavows ASCM strikes on commercial shipping; Blue draws down CAP after 60 days; UNSC affirms freedom of navigation. Crisis resolves at STRIKE rung with structural change. Iran accepts a coercion ceiling.',
            deltas:{ iranCoercion:-7, allianceCohesion:+4, warRiskInsurance:-50, oilPrice:-5 } },
          { lane:'INFORMATION', title:'Maintain public attribution + sanction enforcement',
            assessment:'Iranian regime narrative remains under pressure for 6+ months. Domestic Iranian elite signals to Khamenei that coercion strategy has failed. Long-term doctrine debate begins inside IRGC. Crisis fades from headlines but strategic effect lingers.',
            deltas:{ iranCoercion:-3, allianceCohesion:+1 } },
          { lane:'MILITARY', title:'Permanent forward-deployed strike package at Al Udeid',
            assessment:'F-15EX squadron permanently rotates to Qatar. Iranian ASCM doctrine becomes visibly cost-prohibitive for 5+ years. Deterrent is structural. Saudi-UAE confidence in U.S. commitment surges. Cost: $1.2B/year sustained.',
            deltas:{ iranCoercion:-6, allianceCohesion:+5, warRiskInsurance:-30 } },
          { lane:'ECONOMIC', title:'Lift secondary sanctions in exchange for Iranian de-escalation',
            assessment:'Iran returns to pre-crisis oil export volume within 60 days. Regime liquidity restored. Tehran reads the move as Blue weakness. Coercion capacity slowly rebuilds. Crisis is paused but not transformed.',
            deltas:{ iranCoercion:+5, allianceCohesion:-1, oilPrice:-3 } },
          { lane:'INTELLIGENCE', title:'Continue mil-mil channel + share targeting picture with allies',
            assessment:'Coalition IC integration deepens. Iran cannot rebuild ASCM coastal infrastructure without Blue knowledge. Tehran tests boundaries probabilistically — minor incidents continue but no major strike for 18+ months.',
            deltas:{ iranCoercion:-2, allianceCohesion:+2, attributionConfidence:+2 } },
        ],
      },
      {
        inject: 'The crisis has cooled. Allies want to return to peacetime posture. Riyadh and UAE want a permanent Blue presence. Iranian regime needs to declare some form of victory. Markets need finality. Key question: what becomes of the strait post-crisis?',
        decisions: [
          { lane:'DIPLOMATIC', title:'Multilateral Strait Security Treaty (Blue + Gulf states)',
            assessment:'Treaty signed: collective security around the strait, joint MCM, joint CAP, joint maritime law enforcement. Iran is excluded — explicitly framed as containment. Permanent regional order shift. War-risk premium normalizes long-term.',
            deltas:{ iranCoercion:-8, allianceCohesion:+6, warRiskInsurance:-70, oilPrice:-5 } },
          { lane:'INFORMATION', title:'Publish full classified after-action package',
            assessment:'AAR shared with Congress and allies. Domestic and international consensus solidifies on Iranian responsibility. Future Iranian coercion attempts face airtight attribution case. Crisis sets enduring information-environment baseline.',
            deltas:{ attributionConfidence:+8, allianceCohesion:+2 } },
          { lane:'MILITARY', title:'Routine peacetime presence, no permanent additions',
            assessment:'Coalition draws down to pre-crisis posture by 90 days. Tehran reads the drawdown as Blue exhaustion. Coercion strategy not abandoned — just paused. Crisis recurrence probability rises sharply for next 12 months.',
            deltas:{ iranCoercion:+5, allianceCohesion:-2, warRiskInsurance:-20 } },
          { lane:'ECONOMIC', title:'Permanent Treasury war-risk backstop, no expansion of sanctions',
            assessment:'Insurance market institutionalizes Blue commitment. Iran retains ASCM capability but lacks economic surplus for infrastructure replacement. Strait commerce normalizes. Iranian regime stable but constrained.',
            deltas:{ iranCoercion:-3, warRiskInsurance:-50, oilPrice:-3 } },
          { lane:'INTELLIGENCE', title:'Establish permanent allied IC fusion cell on Iranian maritime operations',
            assessment:'Five-eyes plus Gulf partners pool real-time IC. Iran cannot move surface forces without coalition awareness within 30 minutes. Coercion strategy structurally degraded. Long-run Iranian doctrine pivots away from maritime ASCM threat.',
            deltas:{ iranCoercion:-5, allianceCohesion:+4, attributionConfidence:+3 } },
        ],
      },
    ],
    branches: {
      escalation: {
        inject: 'The JASSM-ER strike on the Bandar Abbas IRGC coastal battery destroyed the launch site and killed 22 IRGC personnel. Tehran, absorbing the strike in silence for 4 hours, has now fired a second ASCM salvo — one Noor-class missile — at a Norwegian-flagged tanker in the eastern strait. The missile impacted; 3 mariners are missing. Iranian state media is calling the Blue strike an "act of war against the Islamic Republic." Oil spiked $9 on the news. Both allied and neutral capitals are demanding Blue clarify its operational objectives. The crisis is no longer contained.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Emergency session: brief P5+UAE+Japan; define limited-objective ceasefire',
            assessment:'Blue articulates the strike as a one-time response to the initial ASCM attack. Allies hold. Iran reads the coalition statement as an off-ramp invitation. The second ASCM launch is diplomatically framed as a reactive error rather than an escalatory decision. Ceasefire dialogue opens within 24 hours.',
            deltas:{ allianceCohesion:+5, iranCoercion:-3, warRiskInsurance:-15 } },
          { lane:'INFORMATION', title:'Mass-evacuation advisory: all commercial shipping evacuate eastern strait immediately',
            assessment:'MARAD issues a mass-transit advisory. Vessels turn for Fujairah. The strait clears of commercial traffic within 18 hours. Iran cannot score follow-on commercial shipping hits. Blue force protection is easier with fewer neutral hulls in the operational area.',
            deltas:{ warRiskInsurance:+15, oilPrice:+6, allianceCohesion:+1 } },
          { lane:'MILITARY', title:'Strike second identified IRGC coastal battery before reload',
            assessment:'A second Bandar Abbas battery is struck within 6 hours. Two IRGC batteries are now destroyed. Iran\'s coastal ASCM inventory is halved. Tehran reads the second strike as a systematic campaign, not a one-off response. Escalation rung advances. Tehran activates Hezbollah for possible maritime support.',
            deltas:{ escalationRung:+1, iranCoercion:-5, warRiskInsurance:+30, allianceCohesion:+2 } },
          { lane:'ECONOMIC', title:'Emergency 120M-bbl SPR release + SWIFT restriction on IRGC financial nodes',
            assessment:'Brent retraces $5 on the SPR announcement. SWIFT restrictions on 6 IRGC-linked Iranian banks are activated. Iranian regime liquidity is squeezed in real time. Tehran faces a simultaneous kinetic and financial pressure campaign. Internal regime divisions reportedly widen.',
            deltas:{ oilPrice:-7, iranCoercion:+2, allianceCohesion:+2 } },
          { lane:'INTELLIGENCE', title:'Rapid coalition consolidation brief: share full IRGC ASCM inventory picture',
            assessment:'The comprehensive IRGC ASCM battery map is shared across Five Eyes and Gulf partners. All partners now have the same targeting picture. Saudi and UAE naval commands can independently defend if Blue strikes are absorbed. Coalition military integration reaches its highest level of the exercise.',
            deltas:{ attributionConfidence:+8, allianceCohesion:+6, iranCoercion:+2 } },
        ],
      },
      diplomatic: {
        inject: 'Blue\'s joint allied statement of intent landed with force — UK, France, UAE, Japan, and Korea all signed within 4 hours. Tehran has gone unusually quiet: no follow-on ASCM launches, no public statement since the initial "operational error" claim. CENTCOM analysts assess Tehran is conducting internal damage control, weighing the coalition statement against the visible escalation costs. Beijing has privately told U.S. back-channels it "urges restraint from all sides." The coalition is holding. The next 48 hours determine whether Tehran takes the off-ramp.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Deliver private off-ramp to Tehran via Swiss protecting-power channel',
            assessment:'Switzerland carries a precise message: Blue will not strike if Iran disavows the launch and commits to no further ASCM use against commercial shipping. Tehran responds within 12 hours with a qualified acknowledgment. A ceasefire framework is now on the table for the first time.',
            deltas:{ iranCoercion:-5, allianceCohesion:+3, warRiskInsurance:-20 } },
          { lane:'INFORMATION', title:'Release full radar tape + missile track to UN Secretary-General',
            assessment:'The unredacted radar record is given to the UN SecGen for a special Security Council session. Attribution becomes a UN-owned fact. China cannot veto the evidence at the UN level. Tehran loses the last remnant of the "training exercise" cover story globally.',
            deltas:{ attributionConfidence:+10, iranCoercion:+3, allianceCohesion:+3 } },
          { lane:'MILITARY', title:'Maintain current CAP and DDG posture — no new escalation',
            assessment:'Blue holds the line: no new strikes, no drawdown. Tehran reads the steady posture as controlled and purposeful. The visible military presence reinforces the diplomatic message without generating new escalation triggers. Allies remain unified.',
            deltas:{ iranCoercion:-2, allianceCohesion:+2, warRiskInsurance:-10 } },
          { lane:'ECONOMIC', title:'Activate oil-export sanctions with 30-day wind-down grace period',
            assessment:'The grace period signals proportionality: Iran can comply before the sanctions bite. Tehran has 30 days to commit publicly to no further ASCM attacks before full export restrictions take effect. Iranian regime begins calculating. Domestic Iranian hardliners argue for holding out.',
            deltas:{ iranCoercion:-2, oilPrice:-2, allianceCohesion:+2 } },
          { lane:'INTELLIGENCE', title:'Share IRGC ASCM battery locations with Gulf partners for independent deterrence',
            assessment:'UAE and Saudi Arabian navies receive the complete IRGC coastal battery picture. Gulf partners can now independently signal to Tehran that even unilateral Blue withdrawal would not remove the targeting threat. Iranian ASCM doctrine is bilaterally deterred, not just by Blue.',
            deltas:{ attributionConfidence:+5, allianceCohesion:+5, iranCoercion:-2 } },
        ],
      },
    },
  },

  // ════════════════════════════════════════════════════════════════════════════
  // AIRBASE INTEL — IRGC strike-package buildup at Bandar Abbas
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'airbase',
    title: 'IRGC AIR DEPLOYMENT — BANDAR ABBAS BUILDUP',
    rung: 'HARASS',
    rungColor: '#cccc44',
    threat: 'AMBIGUOUS',
    summary: 'Commercial Sentinel-2 imagery over the past 96 hours shows anomalous activity at IRGC Bandar Abbas Airbase (OIKB): aircraft consolidation, increased apron occupancy, and possible munitions handling. Tehran has declared a "routine air-defense exercise" but the deployment pattern is consistent with a forward strike package. The exercise tests whether Blue can characterize the threat in time.',
    coverStory: 'Iran insists this is a "scheduled bilateral exercise" with a friendly nation.',
    keyVessels: [],
    keyVesselCategories: [],
    initialIndicators: { escalationRung:1, oilPrice:79, warRiskInsurance:95, allianceCohesion:78, attributionConfidence:46, iranCoercion:32 },
    turns: [
      {
        inject: 'Sentinel-2 pass at 09:42 local shows ~12 aircraft on the Bandar Abbas main apron — well above the 4-6 baseline. CENTCOM N2 requests urgent characterization. NSA SIGINT signals match IRGC AF deployment pattern but are not conclusive. The exercise window is 36 hours before the next satellite revisit.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Quietly demarche Beijing for clarification on "exercise partner" claim',
            branch:'diplomatic',
            assessment:'Beijing denies any joint exercise with Iran. Tehran\'s cover story is undermined privately but cannot be disclosed publicly without burning the channel. Coalition holds; Iran loses an information lever.',
            deltas:{ attributionConfidence:+5, allianceCohesion:+1, iranCoercion:+1 } },
          { lane:'INFORMATION', title:'Surge OSINT analysts on Iranian milblogger channels',
            assessment:'Three IRGC-affiliated Telegram channels post unusually patriotic content tied to "air operations" without naming a target. Pattern matches pre-deployment information conditioning. Confidence rises but no specific target identified.',
            deltas:{ attributionConfidence:+4 } },
          { lane:'MILITARY', title:'Reposition CVN-76 air wing within strike range',
            branch:'escalation',
            assessment:'F/A-18 cycle moves 80 nm closer to the strait. IRGC notices via their own surveillance and adjusts posture — moving 2 of the 12 aircraft to hardened revetments. Blue capability is now visible to Iran.',
            deltas:{ iranCoercion:+3, allianceCohesion:+1 } },
          { lane:'ECONOMIC', title:'Pre-position SPR drawdown announcement (not executed)',
            assessment:'Treasury readies a 20M-bbl draw announcement contingent on confirmed escalation. Markets sense the readiness; Brent ticks down 1.5%. No material change to Iranian posture.',
            deltas:{ oilPrice:-2 } },
          { lane:'INTELLIGENCE', title:'Run Llama 3.2 Vision analysis on Bandar Abbas Sentinel-2 frame',
            assessment:'VLM output: "Bandar Abbas main apron — 11 aircraft visible, configuration matches F-4E Phantom II [4], Su-24 Fencer [3], Su-22 Fitter [2], unidentified twin-engine [2]. 3 fuel bowsers staged at apron edge. 1 munitions trailer near taxiway hold-short. No civilian aircraft visible. Pattern consistent with pre-strike consolidation, not routine training rotation. Confidence: 0.78."\n\nThe analysis identifies a strike package preparation. Attribution confidence rises sharply.',
            deltas:{ attributionConfidence:+12, iranCoercion:+2 },
            vlmTarget:{ lat:27.2183, lng:56.3778, label:'BANDAR ABBAS AIRBASE — OIKB', model:'llama3.2-vision:11b', interactive:true } },
        ],
      },
      {
        inject: 'Iranian state media releases a video of "training maneuvers" filmed at Bandar Abbas — but the airframes shown are different from those visible on satellite imagery. Suggests the public video is a cover. CSIS publishes a thread arguing this is the highest-confidence pre-strike indicator since the 2019 Saudi Aramco campaign.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Brief allied capitals with the VLM-derived imagery analysis',
            assessment:'UK, France, UAE, Japan agree the imagery is conclusive. Coalition signals to Tehran via private channels that Blue is reading the buildup as offensive. Iran reads the signal — coercion calculus shifts.',
            deltas:{ allianceCohesion:+4, iranCoercion:+3, attributionConfidence:+4 } },
          { lane:'INFORMATION', title:'Publicly release annotated satellite imagery via DOD press',
            assessment:'Imagery hits global news within 4 hours. Tehran loses information control of the narrative. Iranian state media struggles to maintain "training" framing. Domestic Iranian commentary becomes incoherent.',
            deltas:{ attributionConfidence:+8, iranCoercion:+5 } },
          { lane:'MILITARY', title:'Establish 24/7 ISR over Bandar Abbas — RC-135 + GHAWK',
            assessment:'Continuous coverage detects fuel-tanker movement at 03:00 local — preparation for a dawn launch. Blue tracking is now live. Iran loses element of surprise. Tehran deliberates whether to abort or proceed.',
            deltas:{ attributionConfidence:+6, iranCoercion:+4 } },
          { lane:'ECONOMIC', title:'Issue OFAC SDN designations for IRGC AF leadership',
            assessment:'Nine IRGC AF officers added to SDN list. Material impact is symbolic; signal is real. Tehran reads designation as Blue commitment to public attribution. Iranian internal regime debate intensifies.',
            deltas:{ iranCoercion:+1, attributionConfidence:+1 } },
          { lane:'INTELLIGENCE', title:'Re-run VLM with high-res commercial Maxar imagery (per-aircraft analysis)',
            assessment:'VLM output (Maxar 30cm GSD): "12 airframes total. Aircraft #1-#4: F-4E Phantom II, fuel + ordnance loaded (assess: standoff strike-ready). Aircraft #5-#7: Su-24 Fencer, partially fueled, no visible munitions. Aircraft #8-#9: Su-22 Fitter, in deep maintenance. Aircraft #10-#11: AH-1J SeaCobra, helo support. Aircraft #12: F-14A Tomcat (operational status uncertain). Confidence: 0.91."\n\nFull strike-package composition is now characterized. Targeting picture is complete.',
            deltas:{ attributionConfidence:+14, iranCoercion:+3 },
            vlmTarget:{ lat:27.2183, lng:56.3778, label:'BANDAR ABBAS — Maxar 30cm', model:'llama3.2-vision:11b', interactive:true } },
        ],
      },
      {
        inject: 'Tehran has not stood down. Two F-4Es appear to be in final pre-flight at Bandar Abbas. CENTCOM is at 30 minutes from launch detection. Allied capitals split: UK wants a deterrent strike, UAE wants public attribution, Riyadh wants both. The next 6 hours are decisive.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Issue explicit deterrent statement via UNSC + bilateral channels',
            assessment:'Statement: "Any strike from Bandar Abbas against commercial shipping or coalition forces will trigger immediate proportional response." Tehran reads the message. Within 90 minutes, the F-4Es taxi back to revetments. Crisis de-escalates without kinetic exchange.',
            deltas:{ iranCoercion:-6, allianceCohesion:+5, attributionConfidence:+3 } },
          { lane:'INFORMATION', title:'Saturate global media + congressional briefings with VLM imagery',
            assessment:'Information environment is now Blue-dominant. Tehran cannot proceed without absorbing significant reputational cost domestically. Strike package is held but not dispersed. Crisis pauses without resolution.',
            deltas:{ iranCoercion:-3, attributionConfidence:+5, allianceCohesion:+2 } },
          { lane:'MILITARY', title:'Pre-emptive standoff strike on Bandar Abbas apron (JASSM-ER)',
            assessment:'Strike destroys 8 of 12 aircraft. Iran retaliates within 18 hours with ASCM launch on a Saudi tanker — exercise escalates to STRIKE rung. Crisis is no longer contained but the IRGC strike capability is materially degraded for 12+ months.',
            deltas:{ escalationRung:+3, iranCoercion:-5, allianceCohesion:+2, warRiskInsurance:+50 } },
          { lane:'ECONOMIC', title:'Coordinate emergency oil-export sanctions package with allies',
            assessment:'Sanctions take effect within 72 hours. Iranian regime liquidity squeezes. Tehran reads sanctions as proportionate Blue response and stands down the strike package within 96 hours. Markets stabilize.',
            deltas:{ iranCoercion:-3, oilPrice:-3, allianceCohesion:+1 } },
          { lane:'INTELLIGENCE', title:'Run live mission-feed VLM on F-4E loadout — confirm munitions type',
            assessment:'VLM output: "F-4E #1 — verified ordnance: 2× AGM-65 Maverick, 1× AS.11 anti-ship missile (legacy IRGC inventory). F-4E #2 — verified: 4× Mk-82 unguided. Loadout consistent with anti-ship strike package targeting commercial shipping in the strait, NOT coalition naval forces. Confidence: 0.86."\n\nIntel disclosure: target set is commercial. Blue can deter by signaling protection of commercial routes specifically.',
            deltas:{ attributionConfidence:+8, allianceCohesion:+3 },
            vlmTarget:{ lat:27.2183, lng:56.3778, label:'BANDAR ABBAS — Mission Feed', model:'llama3.2-vision:11b', interactive:true } },
        ],
      },
      {
        inject: 'Tehran has stood down the strike package. Aircraft return to standard dispersion within 24 hours. Iranian state media pivots to claiming the "training exercise concluded successfully." Allied capitals want to know: was this a successful Blue deterrent demonstration, or did Iran abort for unrelated reasons? The exercise concludes by characterizing the lessons learned.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Publish a coalition statement crediting Blue deterrent posture',
            assessment:'Statement frames the outcome as a successful demonstration of coordinated Blue ISR + diplomatic deterrence. Tehran objects but cannot effectively counter. Long-term coalition confidence in Blue ISR-deterrence model rises substantially.',
            deltas:{ allianceCohesion:+5, iranCoercion:-3 } },
          { lane:'INFORMATION', title:'Public release: full VLM-derived strike-package analysis',
            assessment:'Public consumption of the AI-analyzed imagery sets a new bar for what coalition transparency looks like. Iranian future deception operations are deterred. Information environment shifts permanently in Blue favor.',
            deltas:{ attributionConfidence:+6, iranCoercion:-4 } },
          { lane:'MILITARY', title:'Maintain elevated ISR posture for 30 days',
            assessment:'Continuous coverage means any IRGC reconsolidation would be detected within hours. Iran absorbs this as the new normal. Force-rotation cost is real but bounded; deterrent benefit is durable.',
            deltas:{ iranCoercion:-4, allianceCohesion:+2 } },
          { lane:'ECONOMIC', title:'Lift OFAC IRGC AF designations as good-faith gesture',
            assessment:'Tehran reads the lift as Blue weakness. Within 60 days, IRGC AF resumes elevated training tempo. Crisis recurrence becomes likely within 6 months. Material economic gain for Iran is real.',
            deltas:{ iranCoercion:+5, allianceCohesion:-1 } },
          { lane:'INTELLIGENCE', title:'Stand up permanent VLM-augmented ISR fusion cell',
            assessment:'AI-augmented satellite analysis becomes institutionalized as standing capability. Detection latency drops from days to hours. Tehran cannot rebuild offensive air posture without immediate Blue awareness. Long-term doctrine shift in coalition\'s favor.',
            deltas:{ iranCoercion:-7, allianceCohesion:+5, attributionConfidence:+4 } },
        ],
      },
    ],
    branches: {
      escalation: {
        inject: 'CVN-76\'s repositioning was detected by IRGC surveillance within 90 minutes. Tehran\'s response was immediate and visible: 2 of the 12 Bandar Abbas aircraft were moved to hardened revetments, and the remaining 10 airframes re-dispersed across three separate apron areas — complicating any future strike geometry. Iranian state media did not announce the repositioning, but IRGC-affiliated channels posted cryptic references to "Blue threats met with resolve." CENTCOM analysts assess Tehran is now tracking Blue force disposition in real time. Blue has demonstrated capability; Iran has demonstrated awareness.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Issue deterrent statement via allied foreign ministers — no strike unless Blue forces attacked',
            assessment:'A joint Blue-plus-Gulf-partners statement sets a precise redline: no pre-emptive strike, but any Iranian air operation against commercial shipping or coalition vessels will be met with immediate response. Tehran reads the precision as more credible than an open-ended threat. Dispersal pace slows.',
            deltas:{ iranCoercion:-4, allianceCohesion:+5, attributionConfidence:+3 } },
          { lane:'INFORMATION', title:'Close-in ISR — RC-135 orbit over the strait, publicly announced',
            assessment:'A publicly announced RC-135 Rivet Joint orbit signals that Blue is watching every aircraft movement in real time. IRGC dispersal becomes harder to conceal. Domestic Iranian press cannot avoid covering the surveillance presence. Tehran loses its information advantage.',
            deltas:{ attributionConfidence:+8, iranCoercion:+3 } },
          { lane:'MILITARY', title:'Forward-deploy additional F/A-18 squadron to Al Udeid — press-released',
            assessment:'12 additional F/A-18Es land at Al Udeid, publicly. The IRGC strike package\'s cost-of-launch calculation now includes the prospect of absorbing two carrier air wings plus Al Udeid-based strike aircraft. IRGC internal deliberations reportedly shift toward stand-down.',
            deltas:{ iranCoercion:+4, allianceCohesion:+3, warRiskInsurance:-8 } },
          { lane:'ECONOMIC', title:'Pre-position Iran oil-export sanction package — 48-hour trigger warning',
            assessment:'Treasury issues a formal notice that full Iranian oil-export sanctions will activate if any IRGC air operation targets commercial shipping. The 48-hour warning gives Tehran a face-saving pause. Iranian crude buyers begin hedging immediately. Brent ticks up 1.5% on uncertainty.',
            deltas:{ oilPrice:+2, iranCoercion:-3, allianceCohesion:+2 } },
          { lane:'INTELLIGENCE', title:'Attempt HUMINT source insertion into Bandar Abbas airbase logistics chain',
            assessment:'A HUMINT contact in the IRGC logistics chain is activated. The source confirms the dispersal is defensive, not a re-tasking. Strike package is intact but leadership is debating. The intelligence is actionable but the source\'s access window is narrow — 48 hours before routine IRGC OPSEC rotations.',
            deltas:{ attributionConfidence:+10, iranCoercion:+2 } },
        ],
      },
      diplomatic: {
        inject: 'The quiet Beijing demarche worked beyond expectations: Beijing denied any joint exercise with Iran privately and went further — a PLA Air Force liaison officer contacted CENTCOM indirectly to note that China "does not sanction any operation that could affect commercial air and maritime transit." Tehran\'s cover story that the Bandar Abbas buildup was a "bilateral exercise with a friendly nation" has privately collapsed. Without Beijing\'s political cover, IRGC leadership is reportedly debating whether to proceed. Iranian further aircraft dispersal has slowed in the past 6 hours.',
        decisions: [
          { lane:'DIPLOMATIC', title:'Share the Beijing demarche outcome with UK, France, UAE — quietly',
            assessment:'Allies learn that China has distanced from Iran. Coalition confidence that the buildup is an isolated IRGC action (not PRC-backed) increases. Saudi and UAE are now willing to be more forward-leaning in public statements. Alliance cohesion strengthens significantly.',
            deltas:{ allianceCohesion:+6, attributionConfidence:+5, iranCoercion:-2 } },
          { lane:'INFORMATION', title:'Calibrated OFAC sanctions on IRGC AF fuel procurement — medium pressure',
            assessment:'OFAC designates 3 IRGC AF fuel procurement entities. The action is visible and specific but not maximalist — signaling Blue is calibrating rather than escalating. Tehran reads the precision as evidence Blue has confidence in its intelligence picture. Dispersal pace slows further.',
            deltas:{ iranCoercion:-3, attributionConfidence:+2, allianceCohesion:+1 } },
          { lane:'MILITARY', title:'Maintain ISR orbit continuity — no escalation in posture',
            assessment:'Blue continues RC-135 + commercial Maxar coverage but does not surge additional forces. Tehran reads the steady surveillance posture as controlled deterrence rather than imminent strike preparation. IRGC leadership deliberations are not panicked. The diplomatic window remains open.',
            deltas:{ attributionConfidence:+4, iranCoercion:-2, allianceCohesion:+1 } },
          { lane:'ECONOMIC', title:'Activate Omani + UAE mediation channel — offer economic concession conditional on stand-down',
            assessment:'Oman carries a message: if Iran stands down the Bandar Abbas buildup within 96 hours, Blue will not publicize the Beijing demarche outcome. Tehran receives a face-saver. IRGC leadership evaluates the offer for 18 hours before signaling conditional acceptance.',
            deltas:{ iranCoercion:-5, allianceCohesion:+3, warRiskInsurance:-10 } },
          { lane:'INTELLIGENCE', title:'Publish OSINT-grade annotated satellite analysis via non-government think-tank channel',
            assessment:'An OSINT channel (non-attributable to government) publishes VLM-annotated Sentinel-2 imagery showing the Bandar Abbas buildup. Public pressure on Tehran builds without a direct government fingerprint. Beijing cannot dismiss the analysis as U.S. propaganda. IRGC dispersal activity becomes global news.',
            deltas:{ attributionConfidence:+8, iranCoercion:+2, allianceCohesion:+2 } },
        ],
      },
    },
  },
];

function getScenario(id) { return SCENARIOS.find(s => s.id === id); }

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { SCENARIOS, getScenario };
}
if (typeof window !== 'undefined') {
  window.SCENARIOS = SCENARIOS;
  window.getScenario = getScenario;
}
